# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python2 package test

on:
  push:
    branches: [ dev, master ]
  pull_request:
    branches: [ dev, master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [
          #"2.0",
          "2.0.1",
          #"2.1", "2.1.1", "2.1.2", "2.1.3",
          #"2.2", "2.2.1", "2.2.2",
          #"2.3", "2.3.1", "2.3.2", "2.3.3", "2.3.4", "2.3.5", "2.3.6", "2.3.7",
          #"2.4", "2.4.1", "2.4.2", "2.4.3", "2.4.4", "2.4.5", "2.4.6",
          #"2.5", "2.5.1", "2.5.2", "2.5.3", "2.5.4", "2.5.5",
          #"2.6", "2.6.1", "2.6.2", "2.6.3", "2.6.4", "2.6.5", "2.6.6", "2.6.7", "2.6.8", "2.6.9",
          #"2.7", "2.7.1", "2.7.2", "2.7.3", "2.7.4", "2.7.5", "2.7.6", "2.7.7", "2.7.8", "2.7.9", "2.7.10", "2.7.11", "2.7.12", "2.7.13",
          "2.7.14", "2.7.15", "2.7.16", "2.7.17", "2.7.18",
        ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        id: python-setup
        continue-on-error: true
        run: |
          mkdir ./..bin
          cd ./..bin
          git clone https://github.com/python/cpython.git
          cd cpython
          git checkout v${{ matrix.version }}
          ./configure
          sudo make install
      - name: Set up package
        #        run: |
        #          import os
        #          import os.path
        #          if os.path.isfile("./..bin/cpython/python"):
        #              exit(os.system("sudo ./..bin/cpython/python setup.py install"))
        #          else:
        #              os.system("echo ::warning::Python wasn't installed")
        #        shell: python
        run: |
          ./..bin/cpython/python -V
          sudo ./..bin/cpython/python setup.py install
