# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python3 package test

on:
  push:
    branches: [ master, "3-cpython-0.0", "2-cpython-0.0" ]
  pull_request:
    branches: [ master, "3-cpython-0.0", "2-cpython-0.0" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [
          # "3.0", "3.0.1",
          "3.1", "3.1.1", "3.1.2", "3.1.3", "3.1.4",
          "3.2", "3.2.1", "3.2.2", "3.2.3", "3.2.4", "3.2.5", "3.2.6",
          "3.3.0", "3.3.1", "3.3.2", "3.3.3", "3.3.4", "3.3.5", "3.3.6", "3.3.7",
          "3.4.0", "3.4.1", "3.4.2", "3.4.3", "3.4.4", "3.4.5", "3.4.6", "3.4.7", "3.4.8", "3.4.9", "3.4.10",
          "3.5.0", "3.5.1", "3.5.2", "3.5.3", "3.5.4", "3.5.5", "3.5.6", "3.5.7", "3.5.8", "3.5.9", "3.5.10",
          "3.6.0", "3.6.1", "3.6.2", "3.6.3", "3.6.4", "3.6.5", "3.6.6", "3.6.7", "3.6.8", "3.6.9", "3.6.10", "3.6.11", "3.6.12", "3.6.13",
          "3.7.0", "3.7.1", "3.7.2", "3.7.3", "3.7.4", "3.7.5", "3.7.6", "3.7.7", "3.7.8", "3.7.9", "3.7.10",
          "3.8.0", "3.8.1", "3.8.2", "3.8.3", "3.8.4", "3.8.5", "3.8.6", "3.8.7", "3.8.8", "3.8.9", "3.8.10",
          "3.9.0", "3.9.1", "3.9.2", "3.9.3", "3.9.4", "3.9.5",
        ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        id: python-setup
        continue-on-error: true
        run: |
          mkdir ./..bin
          cd ./..bin
          git clone https://github.com/python/cpython.git
          cd cpython
          git checkout v${{ matrix.version }}
          ./configure
          sudo make install
      - name: Set up package
        #        run: |
        #          import os
        #          import os.path
        #          if os.path.isfile("./..bin/cpython/python"):
        #              exit(os.system("sudo ./..bin/cpython/python setup.py install"))
        #          else:
        #              os.system("echo ::warning::Python wasn't installed")
        #        shell: python
        run: |
          ./..bin/cpython/python -V
          sudo ./..bin/cpython/python setup.py install --github-actions
      - name: Run tests
        run: |
          ./..bin/cpython/python -V
          echo "::group::Checking PATH"
          ./..bin/cpython/python -c "import pyhp;import os;print(*os.getenv('PATH').split(os.pathsep), sep='\n')"
          echo "::endgroup::"
          echo "::group::Tests output"
          ./..bin/cpython/python ./tests/test.py
          echo "::endgroup::"